name: Register Discord Slash Commands

on:
  push:
    branches: [ main ]

jobs:
  sync:
    env:
      DISCORD_API_BASE_URL: https://discord.com/api
      DISCORD_API_VERSION: v8
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
      TOKEN: ${{ secrets.TOKEN }}
    name: sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Reregister All Discord Slash Commands
        run: make sync
